---
driver:
  name: docker
platforms:
  - name: debian12
    image: geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    environment:
      container: docker
    ansible_connection: docker
    ansible_python_interpreter: /usr/bin/python3
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      host_key_checking: false
      retry_files_enabled: false
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
