# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (c) 2023 - present Expiscor Group Inc.
#
# This file is part of Orion's Belt Project (https://github.com/IncudoLABS/orions-belt).
#
# Published by the IncudoLABS.
# Original author: Marko Sarunac <128757181+SaruWiz@users.noreply.github.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Script ID: UNASSIGNED
---
#
# Playbook: UNASSIGNED_configure_vtp.yml
#
# Description: This playbook configures VTP (VLAN Trunking Protocol) on Cisco IOS devices.
#
# Requirements:
#   - Ansible `cisco.ios` collection must be installed (`ansible-galaxy collection install cisco.ios`).
#   - An Ansible inventory file with the target switches defined in `vtp_master` and `vtp_clients` groups.
#   - Connection variables and credentials must be defined in inventory or an encrypted vault.
#
# Example Inventory (e.g., inventory.ini):
#   [vtp_master]
#   switch1 ansible_host=192.168.1.10
#
#   [vtp_clients]
#   switch2 ansible_host=192.168.1.11
#   switch3 ansible_host=192.168.1.12
#
#   [cisco_switches:children]
#   vtp_master
#   vtp_clients
#
#   [cisco_switches:vars]
#   ansible_network_os=cisco.ios.ios
#   ansible_connection=network_cli
#   ansible_become=yes
#   ansible_become_method=enable
#   ansible_user={{ cisco_username }}
#   ansible_password={{ cisco_password }}
#   ansible_become_password={{ cisco_enable_password }}
#

- name: "VTP Configuration: Configure Cisco VTP"
  hosts: all
  gather_facts: false

  vars_prompt:
    - name: vtp_domain
      prompt: "Enter the VTP domain name"
      private: no

    - name: vtp_password
      prompt: "Enter the VTP password"
      private: yes

    - name: vtp_version
      prompt: "Enter the VTP version (1, 2, or 3)"
      private: no
      default: "2"

  tasks:
    - name: Set VTP domain and configure as server
      cisco.ios.ios_vtp:
        domain: "{{ vtp_domain }}"
        password: "{{ vtp_password }}"
        version: "{{ vtp_version }}"
        mode: server
        state: present
      notify: save_config
      when: inventory_hostname in groups['vtp_master']

    - name: Set VTP domain and configure as client
      cisco.ios.ios_vtp:
        domain: "{{ vtp_domain }}"
        password: "{{ vtp_password }}"
        version: "{{ vtp_version }}"
        mode: client
        state: present
      notify: save_config
      when: inventory_hostname in groups['vtp_clients']

  handlers:
    - name: save_config
      listen: "save_config"
      cisco.ios.ios_config:
        save_when: modified 